[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "1.3.3"
decode = { path = "../babyjubjub_ecdlp"}
indicatif = "0.17.7"
clap = { version = "4.4.5", features = ["derive"] }
anyhow = "1.0.75"
