[workspace]
resolver = "2"
members = [
    "hasher.rs/src/wasm",
    "circuit-lib/circuitlib-rs",
    "macros/aligned-sized",
    "macros/light",
    "merkle-tree/*",
    "programs/*",
    "state",
    "test-utils",
    "utils",
    "xtask",
    "examples/token-escrow/programs/*",
    "test-programs/*",
]

[profile.release]
overflow-checks = true

[profile.test]
opt-level = 2
