[workspace]
resolver = "2"
members = [
    "hasher.rs/src/wasm",
    "heap",
    "circuit-lib/light-prover-client",
    "circuit-lib/verifier",
    "macros/aligned-sized",
    "macros/light",
    "merkle-tree/*",
    "programs/account-compression",
    "programs/system",
    "programs/compressed-token",
    "programs/registry",
    "test-utils",
    "utils",
    "xtask",
    "examples/token-escrow/programs/*",
    "test-programs/*",
    "forester",
    "photon-api",
    "sdk"
]

[profile.release]
overflow-checks = true

[profile.test]
opt-level = 2

[workspace.dependencies]
solana-banks-interface = "2.0.1"
solana-program = "2.0.1"
solana-sdk = "2.0.1"
solana-program-test = "2.0.1"
solana-client = "2.0.1"
solana-cli-output = "2.0.1"
solana-transaction-status = "2.0.1"
solana-poseidon = "2.0.1"

anchor-spl = "0.30.1"
anchor-lang = "0.30.1"

borsh ="=0.10.3"

