[workspace]
resolver = "2"
members = [
    "hasher.rs/src/wasm",
    "heap",
    "circuit-lib/light-prover-client",
    "circuit-lib/verifier",
    "macros/aligned-sized",
    "macros/light",
    "merkle-tree/*",
    "programs/account-compression",
    "programs/system",
    "programs/compressed-token",
    "programs/registry",
    "sdk",
    "test-utils",
    "utils",
    "xtask",
    "examples/token-escrow/programs/*",
    "examples/name-service/programs/*",
    "test-programs/*",
    "forester",
    "photon-api",
    "sdk"
]

[profile.release]
overflow-checks = true

[profile.test]
opt-level = 2

[workspace.dependencies]
solana-banks-interface = "=1.18.18"
solana-program = "=1.18.18"
solana-sdk = "=1.18.18"
solana-program-test = "=1.18.18"
solana-client = "=1.18.18"
solana-cli-output = "=1.18.18"
solana-transaction-status = "=1.18.18"
solana-account-decoder = "=1.18.18"
solana-rpc = "=1.18.18"

anchor-lang = "=0.29.0"
anchor-spl = "=0.29.0"

spl-token = "=4.0.0"

proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }

tokio = { version = "1.39.1", features = ["rt", "macros", "rt-multi-thread"] }