[package]
name = "name-service"
version = "0.6.0"
description = "Simple DNS service on Light Protocol"
edition = "2021"
rust-version = "1.75.0" 
license = "Apache-2.0"

[lib]
crate-type = ["cdylib", "lib"]
name = "name_service"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = ["idl-build"]
test-sbf = []
bench-sbf = []
idl-build = ["anchor-lang/idl-build", "light-sdk/idl-build"]

[dependencies]
anchor-lang = { workspace = true, features = ["init-if-needed"] }
borsh = "0.10"
light-hasher = { path = "../../../../merkle-tree/hasher", version = "1.0.0", features = ["solana"] }
light-macros = { path = "../../../../macros/light", version = "1.0.0" }
light-sdk-macros = { path = "../../../../macros/light-sdk-macros", version = "0.1.0" }
light-sdk = { path = "../../../../sdk", version = "0.8.0" }
light-utils = { path = "../../../../utils", version = "1.0.0" }
light-verifier = { path = "../../../../circuit-lib/verifier", version = "1.0.0" }

[target.'cfg(not(target_os = "solana"))'.dependencies]
solana-sdk = { workspace = true }

[dev-dependencies]
light-test-sdk = { path = "../../../../test-sdk", version = "0.8.0" }
photon-api = { path = "../../../../photon-api", version = "0.44.0" }
solana-client = { workspace = true }
tokio = { workspace = true }
