[package]
name = "test-batch-transactions"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"
resolver = "2"

[lib]
crate-type = ["cdylib", "lib"]
name = "test_batch_transactions"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []
test-sbf = []

[dependencies]
anchor-lang = {version="0.29.0", features=["init-if-needed"]}
anyhow = "1.0.86"
# solana-program = "1.18.17"

[dev-dependencies]
solana-banks-interface = "1.18.17"
solana-program = "1.18.17"
solana-sdk = "1.18.17"
solana-client = "1.18.17"
solana-cli-output = "1.18.17"
solana-transaction-status = "1.18.17"
solana-account-decoder = "1.18.17"
solana-rpc = "1.18.17"
tokio = "1.39.2"
light-test-utils = {path = "../../test-utils"}
forester = {path = "../../forester"}
bb8 = "0.8.5"
futures = "0.3.30"
reqwest = { version = "0.11", features = ["json", "rustls-tls"]  }

[profile.bench]
debug = true