[package]
name = "zk-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
light-poseidon = "0.1.1"
ark-bn254 = "0.4.0"
ark-ff = "0.4.0"
js-sys = "0.3.64"
hex = { version = "0.4.3", features = [] }