[package]
name = "light-hasher"
version = "0.2.1"
description = "Trait for generic usage of hash functions on Solana"
repository = "https://github.com/Lightprotocol/light-protocol"
license = "Apache-2.0"
edition = "2021"

[features]
solana = ["solana-poseidon", "solana-program"]

[dependencies]
light-poseidon = "0.2.0"
solana-poseidon = { workspace = true, optional = true }
solana-program = { workspace = true, optional = true }
thiserror = "1.0"

[target.'cfg(not(target_os = "solana"))'.dependencies]
ark-bn254 = "0.4.0"
sha2 = "0.10"
sha3 = "0.10"
