[package]
name = "verifier_program_one"
version = "0.1.0"
description = "Verifier program 1 can verify 10 inputs and 2 outputs without additional public inputs."
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "verifier_program_one"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = { version = "0.25.0"}
anchor-spl = "0.25.0"
solana-security-txt = "0.1.0"
merkle_tree_program = { path = "../merkle_tree_program", features = ["cpi"] }

#solana
solana-program = { path = "../../../../solana/sdk/program"}

# Light Deps
groth16-solana = {path = "../../../groth16-solana"}
light-verifier-sdk = {path = "../../../light-verifier-sdk"}
