[package]
name = "account-compression"
version = "0.4.1"
description = "Solana account compression program"
repository = "https://github.com/Lightprotocol/light-protocol"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "account_compression"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
custom-heap = ["light-heap"]
mem-profiling = []
default = ["custom-heap"]
test-sbf = []
bench-sbf = []

[dependencies]
aligned-sized = { workspace = true }
anchor-lang = { workspace = true }
bytemuck = { workspace = true }
light-bounded-vec = { workspace = true }
light-hash-set = { workspace = true }
light-hasher = { workspace = true }
light-heap = { workspace = true, optional = true }
light-concurrent-merkle-tree = { workspace = true }
light-indexed-merkle-tree = { workspace = true }
light-utils = { workspace = true }
num-bigint = { workspace = true }
num-traits = { workspace = true }
solana-security-txt = { workspace = true }

[target.'cfg(not(target_os = "solana"))'.dependencies]
solana-sdk = { workspace = true }
