[features]
seeds = false

[test.validator]
url = "https://api.devnet.solana.com"

# merkle tree
[[test.validator.clone]]
address = "HKwwxmW1WroCFXa5y4txaGgzzQ1S7r8fU16aqq78w3Et"

[programs.localnet]
verifier_program = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
merkle_tree_program = "2c54pLrGpQdGxJWUAoME6CReBrtDbsx5Tqx4nLZZo6av"
attacker_program = "3KS2k14CmtnuVv2fvYcvdrNgC94Y11WETBpMUGgXyWZL"

[programs.mainnet]
verifier_program = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"
merkle_tree_program = "2c54pLrGpQdGxJWUAoME6CReBrtDbsx5Tqx4nLZZo6av"
attacker_program = "3KS2k14CmtnuVv2fvYcvdrNgC94Y11WETBpMUGgXyWZL"

 [test]
startup_wait = 100_000
[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test_merkle_tree = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/merkle_tree_program.ts"
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/verifier_program.ts"
