[package]
name = "decode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "src/lib.rs"

[dependencies]
ark-jubjub = { git = "https://github.com/Shigoto-dev19/ark-babyjub.git", package = "ark-babyjub" }
ark-ff = { version = "0.4.0", default-features = false }
ark-ec = { version = "0.4.0", default-features = false }
ark-std = { version = "0.4.0", default-features = false }
itertools = "0.11.0"
serde = { version = "1.0.188", features = ["derive"] }
lazy_static = "1.4.0"
bincode = "1.3.3"
serde_json = "1.0.105"
serde_derive = "1.0.188"
num-bigint = "0.4.4"

[dev-dependencies]
criterion = "0.5.1"

[[bench]]
name = "bench_decode"
harness = false