[package]
name = "test-release"
version = "0.4.0"
description = "Generalized token compression on Solana"
repository = "https://github.com/Lightprotocol/light-protocol"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "test_release"

[features]
default = []



[dependencies]
anchor-lang = "0.29.0"
anchor-spl = {version="0.29.0", default-features=false}
# aligned-sized = { version = "0.2.0", path = "../../macros/aligned-sized" }
# account-compression = { version = "0.4.0", path = "../account-compression", features = ["cpi", "no-idl"] }
# light-system-program = { version = "0.4.0", path = "../system", features = ["cpi"] }
# solana-security-txt = "1.1.0"
# light-hasher = { version = "0.2.0", path = "../../merkle-tree/hasher" }
# light-heap = { version = "0.2.0", path = "../../heap", optional = true }
# light-utils = { version = "0.2.0", path = "../../utils" }
# solana-program = "1.18.11"
# spl-tlv-account-resolution = "0.3.0"
# 
# [target.'cfg(not(target_os = "solana"))'.dependencies]
# solana-sdk = "1.18.11"

[dev-dependencies]
rand = "0.8.5"