[package]
name = "light-sdk"
version = "0.2.1"
description = "ZK Compression on Solana"
repository = "https://github.com/Lightprotocol/light-protocol"
license = "Apache-2.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "light_sdk"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
custom-heap = ["light-heap"]
mem-profiling = []
default = ["custom-heap"]
test-sbf = []
bench-sbf = []

[dependencies]
account-compression = { workspace = true }
aligned-sized = { workspace = true }
anchor-lang = { workspace = true }
borsh = { workspace = true }
bytemuck = { workspace = true }
groth16-solana = { workspace = true }
light-concurrent-merkle-tree = { workspace = true }
light-hasher = { workspace = true }
light-heap = { workspace = true, optional = true }
light-macros = { workspace = true }
light-system-program = { workspace = true }
light-utils = { workspace = true }
light-verifier = { workspace = true }

[target.'cfg(not(target_os = "solana"))'.dependencies]
solana-sdk = { workspace = true }

[dev-dependencies]
# Local crates
light-hash-set = { workspace = true }
light-indexed-merkle-tree = { workspace = true }
light-merkle-tree-reference = { workspace = true }
light-prover-client = { workspace = true }

# External crates
lazy_static = { workspace = true }
rand = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }

solana-banks-interface = { workspace = true }
solana-cli-output = { workspace = true }
solana-program-test = { workspace = true }
solana-sdk = { workspace = true }
serde_json = { workspace = true }
