[template]
cargo_generate_version = ">=0.18.2"

[placeholders.rust-name]
type = "string"
prompt = "Name of the Rust crate (snake_case)"

[placeholders.program-id]
type = "string"
prompt = "Solana program ID"
default = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[placeholders.light-merkle-tree-program-version]
type = "string"
prompt = "Merkle tree program version"

[placeholders.light-system-program-version]
type = "string"
prompt = "Native PSP version"

[placeholders.light-system-program]
type = "string"
prompt = "Native PSP"

[placeholders.light-macros-version]
type = "string"
prompt = "Native PSP"

[placeholders.light-verifier-sdk-version]
type = "string"
prompt = "Native PSP"

[placeholders.type-prefix]
type = "string"
prompt = "Sub cli type (psp, circom)"
default = "psp"