on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - ready_for_review
      - reopened

name: docker-build-test
jobs:
  docker-build-test:
    name: docker-build-test
    runs-on: buildjet-16vcpu-ubuntu-2204
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - run: npm ci

      - name: Setup and build
        uses: ./.github/actions/setup-and-build

      - name: Run Docker build test
        run: ./scripts/testDockerRelayer.sh
