name: Release prover binaries
on:
  push:
    tags:
      - '*'
    branches:
      - main
    paths:
      - "gnark-prover/**"
      - ".github/workflows/prover-test.yml"
      - ".github/workflows/prover-release.yml"
  pull_request:
    branches:
      - main
    paths:
      - "gnark-prover/**"
      - ".github/workflows/prover-test.yml"
      - ".github/workflows/prover-release.yml"
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Build artifacts
        run: |
          cd gnark-prover
          for cfgstr in "darwin amd64" "darwin arm64" "linux amd64" "windows amd64"; do
            cfg=( "$cfgstr" )
            export GOOS="${cfg[0]}"
            export GOARCH="${cfg[1]}"
            export CGO_ENABLED=0
            go build -o prover-"$GOOS"-"$GOARCH"
          done

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            prover-darwin-amd64
            prover-darwin-arm64
            prover-linux-amd64
            prover-windows-amd64